// Lock file index - tracks completed modules for this session
export const sessionLock = {
  timestamp: Date.now(),
  completed: [
    'project-setup',
    'tailwind-config',
    'api-modules',
    'auth-context',
    'toast-context',
    'reusable-components',
    'auth-layout',
    'app-layout',
    'auth-pages',
    'dashboard',
    'settings',
    'terms',
    'staff',
    'students',
    'student-detail',
    'guardians',
    'classes',
    'subjects',
    'enrollments',
    'scores',
    'attendance',
    'reports',
    'analytics',
    'notifications',
    'routes',
  ],
};